---
title: "Group04 Presentation R4BDS"
author: "Eric Calaveras - Sol Escamilla - Beatriz García - Lucía López - Diego Medina"
format: revealjs
editor: visual
---

## Content
Group 04 R for Bio Data Science
Eric Calaveras
Sol Escamilla
Beatriz García
Lucía López
Diego Medina

Microarray data processing and visualization

## Introduction

Dataset content:

-   x: probes IDs and  gene expression values of each sample

-   y: diagnosis (symptomatic, control)

The desired output to start working with the dataset is a tibble with tidy data:

1.  Each row is an observation
2.  Each column is a variable
3.  Each cell is a single value

## Wrangling I: initial tibble

Explicar por qué necesitamos agregar sample/diagnosis y convertir a tibble

## Wrangling II: Pivot_longer

Explicar que pasar los probes a filas es el paso más importante para tener "tidy data", y por qué esto facilita cualquier análisis despues.

## Bioconductor

Explicar el annotation package

Gracias al paquete hgu133a.db (database) podemos asociar los probes a genes a partir de la columna SYMBOL. (código de Sol)

## Obtaining gene-level data

Que se vea cómo varios probes de un mismo gen se colapsan en un solo valor promediando.

Explicar que en microarrays varios probes mapean a un mismo gen, reduciendo ruido y facilitando hacer estudios.

## Log2 transformation and categories

Poner en la diapo:
- gráfico del antes/despues
- distribución raw vs log2

Explicar: 
- Log2 reduce la diferencia entre valores bajos y altos.
- Mejora visualización y normaliza la escala.
- Explicar por qué aparecen valores negativos.

## Visualization 1


```{r, echo=FALSE}


```

## Visualization 2



## Discussion

Gracias a usar todas estas herramientas hemos podido encontrar genes mas singnificativos e importantes en esta enfermedad
